filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/duijie/iwc/logs/*.*
  fields:
    systemName: "dj-tjhg"
    moduleName: ""
    subproName: ""
    subprodgsd: ""
    ip: "10.10.129.121"
    port: "30102"
  scan_frequency: 10s
  harvester_buffer_size: 16384
  max_bytes: 10485760
  spool_size: 1024
  idle_timeout: 10s
  timeout: 10s
  multiline.pattern: '^\d{4}\-\d{2}\-\d{2}\s\d+\:\d+\:\d'
  multiline.negate: true
  multiline.match: after
  max_lines: 500
  close_removed: true
  clean_removed: true
  close_older: 1h
  force_close_files: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
name: 10.10.129.121-10.10.130.149:6673
output.logstash:
  hosts: ["10.10.130.149:6673"]
xpack.monitoring:
    enabled: true
    elasticsearch:
        hosts: ["http://10.10.130.149:9910","http://10.10.130.149:9911"]
        username: "monitor"
        password: "123456"

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

